apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
  name: influxdb
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: influxdb
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      serviceAccountName: example-influxdb
      containers:
        - envFrom:
            - secretRef:
                name: influxdb-creds
          image: docker.io/influxdb:latest
          imagePullPolicy: IfNotPresent
          name: influxdb
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: var-lib-influxdb
      volumes:
        - name: var-lib-influxdb
          persistentVolumeClaim:
            claimName: influxdb
