apiVersion: v1
kind: ConfigMap
metadata:
  name: config3
  labels:
    name: config3
  namespace: default
data:
  conf.json: '{"Hop":{"1" :null, "2" :null }, "Hostname":"redis-service3", "Type":"sleep"}'
