apiVersion: v1
kind: PersistentVolume
metadata:
  name: elk-pv
  namespace: logging
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 10Gi
  claimRef:
    name: elk-pvc
    namespace: logging
  hostPath:
    path: "/var/log/elk/"