apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elk-pvc
  namespace: logging
spec:
  storageClassName: manual
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 10Gi
  volumeName: elk-pv