apiVersion: v1
kind: Service
metadata:
  name: redis-service
spec:
  selector:
    app: redis-demo
  ports:
    - name: http
      port: 5000
      targetPort: 5000
    - name: tcp
      port: 6379
      targetPort: 6379
  type: LoadBalancer
# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: example-demo
#   labels:
#     account: demo
