apiVersion: v1
kind: Service
metadata:
  labels:
    app: influxdb
  name: influxdb
  namespace: edge-namespace
spec:
  ports:
    - name: http
      port: 8086
  selector:
    app: influxdb
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: example-influxdb
  namespace: edge-namespace
  labels:
    account: influxdb
